### ISSUE TITLE
select options value

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#100]
## Description

Para evitar possíveis conflitos entre os nomes de municípios e etapas de ensino no banco de dados, vamos exibir os nomes corretamente na tela, mas ao encaminhar na rota para o backend, passaremos o id do município no IBGE e uma sigla para as etapas de ensino.

## Tasks
- [ ] Modificar o componente select para que ele receba um array de objetos com chave name e value. A chave name será utiliada para exibir o nome na tela, e value será utilizada para armazenar o ID, ou a sigla que será encaminhada para o backend.
- [ ] Modificar a listagem de municípios, adicionando o ID do IBGE, deve-se refazer a busca na API do IBGE e salvar no documento no novo formato.
- [ ] Modificar a listagem de etapas de ensino, adicionando nas chaves value: EF1, EF2, EM, Todos.
- [ ] Modificar as demais listagens, nesses casos, pode-se manter o mesmo valor em value e name a princípio.

## Tests / Evaluation
- [ ] Conferir e adaptar os testes de componente do select

## Responsible Parties
@JoaoPedrooSS
