### ISSUE TITLE
graphic information

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#101]
## Description
Eu, como usuário, desejo entender melhor o que está sendo exibido no gráfico, como fontes, métodos de tratamento dos dados, possíveis erros entre outras informações importantes para garantir transparência dos dados exibidos.

## Tasks
- [ ] Fazer, para cada um dos 3 componentes gráficos, uma janela flutuate que exibirá as informações de transparência, modelo POPUP.
- [ ] A janela deve ser exibida ao se clicar em um icone de informação, procurar na lib phosphor icons que deverá estar localizado próximo ao  gráficos.
- [ ] A tela principal deve ficar levemente escurecida quando a janela estiver aberta
- [ ] A janela deve ser responsiva, e todos os tamanhos de tela devem ser atendidos
- [ ] Deve haver um botão para fechar a janela
- [ ] A janela deve ser um novo componente, já que será reaproveitado três vezes.
- [ ] O texto das janelas e o design deve ser decidido em grupo, a princípio usar texto genérico.

## Tests / Evaluation
- [ ] Fazer os testes unitários do componente

## Responsible Parties
@jlucasiqueira
