### ISSUE TITLE
clean code

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#105]
## Description
Varrer todo o código, em todos os componentes, e altera-lo para seguir um padrão
## Tasks
- [ ] Implementar testes para que todos os arquivos atinjam 100% de cobertura, analisar as linhas que faltam na tabela de coverage
- [ ] Padronizar testes, tentar deixar uma estrutura semelhante em todos
- [ ] Modificar nome de variáveis (padronizar e usar inglês)
- [ ] Modificar nome de métodos ( padronizar e usar ingles)
- [ ] Modificar todos os locais necessários, tomando cuidado com as importações.
- [ ] O unico lugar que deve haver português é dentro dos services passando as query params para o backend.
- [ ] A formatação do código deve estar harmônica(variáveis juntas, states juntos, métodos, effects etc.)
- [ ] No arquivo de dados dos filtros e gráficos, organizar a ordem e os nomes dos dados, e nos gráficos alterar para dados iguais, todos 100 por exemplo)
- [ ] Para o conjunto de variáveis que armazenam o state do filtro de um gráfico, analisar a possibilidade de implementar um objeto, tendo assim três objetos, um para cada gráfico. Veja exemplo:

```typescript
// arquivo service:
export interface ReportFilter {
  planId?: string;
  status?: string;
  paymentStatus?: string;
  search?: string;
  page: number;
}
// arquivo search/page:
  const [filters, setFilters] = useState<ReportFilter>({
    page: 1,
    paymentStatus: 'paid',
    status: 'active',
    planId: '',
    search: '',
  });

// no componente:
 onChange={(e) => setFilters({ ...filters, search: e.target.value })}
```  

Para a modificação proposta acima, deve-se atentar ao service, pois será necessária modificação

## Tests / Evaluation
Caso haja necessidade, alterar os testes unitários que forem afetados.
Verificar se todos os filtros estão sendo setados com sucesso e passados corretamente ao backend.

## Responsible Parties
@JoaoPedrooSS
