### ISSUE TITLE
usable ranking

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#118]
## Description
O componente de ranking deve passar a conter uma listagem completa de municípios. 
Junto aos filtros, teremos um campo de busca, para buscar por município ou índice dentro do ranking. Quando a pesquisa for feita, deve-se exibir aquele município/posição correspondente e algumas posições acima e abaixo daquele município. A busca deve ser case insensitive.
A busca deve ser feita tanto por município quanto por posição, pensar em lógica para dois campos de busca.
A ordenação será feita no frontend conforme acordado.

## Tasks
- [x] Implementar lista completa no componente de ranking.
- [x] Exibir apenas 10 elementos no ranking, os 10 primeiros de acordo com a ordem.
- [x] Para busca por município, considera-se utilizar o select com busca, para que haja apenas um município correspondente
- [x] Pensar em lógica para buscar por município ou posição. ex: sempre que buscar por posição, limpar o filtro de município e vice-versa, para evitar conflitos de busca simultânea. (Possíveis alterações nos componentes existentes são consideráveis para atender o caso, tomando cuidado para não quebrar os demais usos)

## Responsible Parties
@rafgpereira
