### ISSUE TITLE
responsive filters

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#119]
## Description
Atualmente temos problemas com alguns filtros, corrigir a responsividade mantendo boa legibildiade e design da página mobile.

## Tasks
- [ ] Os filtros de todos os gráficos, quando em telas menores, não podem quebrar o tamanho máximo. Para testar, selecione sempre os maiores nomes disponíveis dentro de cada filtro. Considerar usar flex-wrap para que quando necessário, haja quebra de linha, caso não funcione, deixar cada filtro em uma linha em telas menores. Os principais filtros a serem tratados: Município e Etapa de ensino.
- [ ] Todos os filtros, de todos os gráficos não podem exibir nomes com '...' Ex: Ensino Funda... , pois atrapalha a legibilidade, principalmente para casos que há diferença apenas no final, como Ensino Fundamental 1 e 2. 

## Tests / Evaluation
- [ ] Selecionar em mobile, todos os filtros com os maiores nomes possíveis. Não pode exceder a tela em nenhum caso.
- [ ] Selecionar em mobile, diferentes critérios nos filtros, ex: um município grande e uma etapa pequena, entre outros, para avaliar todas as possibilidades.
- [ ] Testar também em desktop, para verificar se as mudanças não afetaram a disposição normal dos filtros.

## Responsible Parties
@JoaoPedrooSS
