### ISSUE TITLE
graphics order

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#151]
## Description
Atualizar o frontend com as sugestões de melhoria da professora Carla.

## Tasks
- [ ] Remover a opção Todos do filtro de Etapa de ensino do Ranking;
- [ ] Colocar o Ranking como primeiro componente da tela, seguido pelo de Matrículas e Indicadores
- [ ] Detalhar melhor os textos, tanto o texto incial de Desigualdade Racial quanto os textos descritores de cada gráfico
- [ ] Colocar o link para a fonte dos dados nos popups de cada gráfico
- [ ] No ranking, melhorar a descrição inicial dele, e também no popup, deixando o método de calculo mais compreensivel: adicionar equação para melhor visualização do cálculo.
- [ ] Implementar possíveis melhorias de design que acharem viável após a alteração da ordem dos componentes.

## Tests / Evaluation
- [ ] Alterar os testes unitários, caso seja necessário
- [ ] Testar a responsividade após as alterações, principalmente dos popus.

## Responsible Parties
@JoaoPedrooSS @jlucasiqueira
