### ISSUE TITLE
Frontend leveling

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#45]
## Description

Estudar, praticar e nivelar o conhecimento do time sobre requisições e manipulação 
de dados no frontend, visando o desenvolvimento da página Pesquisa do 
EducaMinas. 

O usuário deve inserir um termo de busca, e, ao clicar em pesquisar, devem ser 
exibidas as cidades encontradas a partir do termo inserido com seus respectivos 
estados. 

Após a listagem do nome das cidades e seus estados, deve ser exibido um gráfico 
de setores (pizza) que ilustre a quantidade de cidades com cada nível de acesso dos 
diários municipais das cidades encontradas (0-3).

Utilize:

- Linguagem: Typescript 
- Biblioteca/Framework: React ou Next 
- Biblioteca (gráficos): a escolha 
- HTTP:  Axios 
- Testes: Postman 
- Deploy: Netlify 
- API: Querido Diário 

## Tasks

- [ ] Barra de pesquisa
- [ ] Listagem de municípios a partir da pesquisa
- [ ] Gráfico de setores com nível de acesso das cidades
- [ ] Deployment

## Tests / Evaluation

- [ ] Site funcional online
- [ ] Funcionalidades atendidas

## Responsible Parties

@JoaoPedrosilvaSousa @jlucasiqueira

**Comment by JoaoPedrosilvaSousa** [comment]
Site feito para estudo de nivelamento: https://busca-level.netlify.app
