### ISSUE TITLE
Configure eslint

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#48]
## Description
Configurar o eslint do projeto e o formatador padrão da linguagem

## Tasks

- [x] Configurar formatador padrão
- [x] Configurar eslint
- [x] Configurar extensões recomendadas

## Tests / Evaluation
O IDE deve:
- [x] Formatar e identar corretamente com autosave
- [x]  Apontar os erros de lint

## Responsible Parties
@rafgpereira
