### ISSUE TITLE
Implement filters on the search page

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#49]
## Description

Criar componente de filtro para a página de pesquisa

## Tasks

- [ ] Adicionar label
- [ ] Adicionar selection
- [ ] Adicionar options
- [ ] Adicionar design
- [ ] Implementar em um gráfico

## Tests / Evaluation

- [ ] Componente estilizado
- [ ] Componente com todas os requisitos (label, selection, options)
- [ ] Aprovação do front-end

## Responsible Parties
@JoaoPedrosilvaSousa
