### ISSUE TITLE
Create ranking component

### ISSUE THREAD

**Issue by rafgpereira** [unb-mds/2024-1-EducaMinas-frontend#54]
## Description

Criar um componente de ranking. Este componente deve receber um array de objetos. Os objetos devem conter: nome: string, valor: number e critério de ordenação: string.

## Tasks

- [ ] Ordenação da lista de acordo com o critério

## Tests / Evaluation

- [ ] Aprovação do frontend
- [ ] Ordenação seguindo os critérios

## Responsible Parties
@JoaoPedrosilvaSousa @jlucasiqueira @rafgpereira
